### ISSUE TITLE
 config.py文件中添加SCKEY 没有作用 

### ISSUE THREAD

**Issue by 666668113** [X1A0CA1/xiaobei_auto_health#10]
下载到本地运行时在 config.py文件中添加SCKEY 没有作用 想问一下作者本地运行在哪里添加SCKEY 微信推送
![屏幕截图 2022-04-11 235433](https://user-images.githubusercontent.com/71271253/162781134-74818e57-4bfd-4635-84ad-723812b05cfc.png)

**Comment by 666668113** [comment]
好像解决了在main.py文件件中添加 sckey = config.sckey 就似乎可以了
![屏幕截图 2022-04-12 002432](https://user-images.githubusercontent.com/71271253/162786370-e20908d6-1514-4e5b-84f1-dbde6eebde31.png)
运行之后日志是这样的
![屏幕截图 2022-04-12 002527](https://user-images.githubusercontent.com/71271253/162786532-b8a3481a-673d-4a2a-845a-5deaa81e21ed.png)
微信推送
![IMG_6424](https://user-images.githubusercontent.com/71271253/162786666-f6278de0-eb93-4375-924b-a788036f464d.PNG)
目前还不确定影不影响其他的状态
第一次尝试

**Comment by X1A0CA1** [comment]
所有环境变量就这么多
<img width="572" alt="image" src="https://user-images.githubusercontent.com/52635310/163665489-1098971c-0bbf-480f-b6f9-855076e69a09.png">

其他东西应该不会影响，看你个人需求缺啥补啥了。
